apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v52shfrjd-python 
  janus-idp.io/tekton: v52shfrjd-python
  backstage.io/kubernetes-id: v52shfrjd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v52shfrjd-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  